include: package:flutter_lints/flutter.yaml

linter:
  rules:
    always_declare_return_types: true
    annotate_overrides: false
    camel_case_extensions: true
    camel_case_types: true
    curly_braces_in_flow_control_structures: true
    directives_ordering: true
    lines_longer_than_80_chars: false
    prefer_constructors_over_static_methods: false
    prefer_relative_imports: true
    prefer_single_quotes: true
    sort_constructors_first: false
    sort_pub_dependencies: false
    valid_regexps: true
    implementation_imports: false
