name: finance
description: Finance Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  cloud_firestore: ^2.5.3
  equatable: ^2.0.3
  firebase_auth: ^3.1.3
  firebase_core: ^1.7.0
  fl_chart: ^0.40.0
  flutter:
    sdk: flutter
  flutter_local_auth_invisible: ^2.0.0
  flutter_localizations:
    sdk: flutter
  flutter_secure_storage: ^4.2.1
  flutter_svg: ^0.22.0
  get: ^4.3.8
  google_fonts: ^2.1.0
  google_nav_bar: ^5.0.5
  google_sign_in: ^5.1.1
  iconly: ^1.0.1
  intl: ^0.17.0
  lottie: ^1.2.1
  provider: ^6.0.1
  staggered_grid_view_flutter: ^0.0.4

dev_dependencies:
  flutter_launcher_icons: ^0.9.2
  flutter_lints: ^1.0.4
  flutter_native_splash: ^1.2.4
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - lib/ui/assets/animations/
    - lib/ui/assets/icons/
    - lib/ui/assets/launcher_icon/
    - lib/ui/assets/splash/

flutter_icons:
  # flutter pub run flutter_launcher_icons:main

  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "lib/ui/assets/launcher_icon/icon.png"
  adaptive_icon_background: "lib/ui/assets/launcher_icon/background.png"
  adaptive_icon_foreground: "lib/ui/assets/launcher_icon/foreground.png"

flutter_native_splash:
  # flutter pub run flutter_native_splash:create
  # flutter pub run flutter_native_splash:remove

  # color: "#FCFCFC"
  background_image: "lib/ui/assets/splash/splash_light.png"
  # image: lib/ui/assets/splash/splash_light.png

  # color_dark: "#303030"
  background_image_dark: "lib/ui/assets/splash/splash_dark.png"
  # image_dark: lib/ui/assets/splash/splash_dart.png

  android: true
  ios: true
  web: false

  # To hide the notification bar, use the fullscreen parameter.  Has no affect in web since web
  # has no notification bar.  Defaults to false.
  # NOTE: Unlike Android, iOS will not automatically show the notification bar when the app loads.
  #       To show the notification bar, add the following code to your Flutter app:
  #       WidgetsFlutterBinding.ensureInitialized();
  #       SystemChrome.setEnabledSystemUIOverlays([SystemUiOverlay.bottom, SystemUiOverlay.top]);
  #fullscreen: true

  # android12: true
